### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by Frozies** [Frozies/petal-patch#47]
Remove nodemon from the start script. the server crashed for some reason after launching.

[nodemon] 2.0.7
out: [nodemon] to restart at any time, enter `rs`
out: [nodemon] watching path(s): *.*
out: [nodemon] watching extensions: js,mjs,json
out: [nodemon] starting `node ./bin/www`
err: internal/modules/cjs/loader.js:883
err:   throw err;
err:   ^
err: 
err: Error: Cannot find module 'http-errors'
err: Require stack:
err: - /petal-patch-server/petal-patch-server/app.js
err: - /petal-patch-server/petal-patch-server/bin/www
err:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
err:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
err:     at Module.require (internal/modules/cjs/loader.js:952:19)
err:     at require (internal/modules/cjs/helpers.js:88:18)
err:     at Object.<anonymous> (/petal-patch-server/petal-patch-server/app.js:1:19)
err:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
err:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
err:     at Module.load (internal/modules/cjs/loader.js:928:32)
err:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
err:     at Module.require (internal/modules/cjs/loader.js:952:19) {
err:   code: 'MODULE_NOT_FOUND',
err:   requireStack: [
err:     '/petal-patch-server/petal-patch-server/app.js',
err:     '/petal-patch-server/petal-patch-server/bin/www'
err:   ]
err: }
out: [nodemon] app crashed - waiting for file changes before starting...

**Comment by Frozies** [comment]
Added a correct script for running the server without nodemon in PR #48. missing module still persists

**Comment by Frozies** [comment]
I changed line 20 of the dockerfile from "COPY . /petal-patch-server" to "COPY . /petal-patch-server/petal-patch-server". in PR #49  I believe that caused npm to fail to find the start script. im not going to dive to find out, im just going to change it back now.

**Comment by Frozies** [comment]
build #50 failed. I've changed the line 16 of the dockerfile from "COPY . /petal-patch-server" to "COPY . /petal-patch-server/petal-patch-server" I'm also manually installing all of the dependencies.

**Comment by Frozies** [comment]
#51 Error: Cannot find module 'puppeteer' WTF I am manually installing it already.... Im going to install it again i guess... I really dont know why its not installing when I run npm install

**Comment by Frozies** [comment]
#52 didnt have curl -- fail flag. added that in #53

**Comment by Frozies** [comment]
Why is it still running on the monorepo package.json

**Comment by Frozies** [comment]
Now the path is three petal-patch-servers deep in #55

**Comment by Frozies** [comment]
#58 ACTUALLY WORKS. but now github actions doesnt switch over... im missing something here, i re-added the silent tag to curl, but i honestly dont understand what is entirely going on.

**Comment by Frozies** [comment]
I need to figure out the link between github actions and getting a response back from the server. Also finish reading https://blog.logrocket.com/zero-downtime-deploys-with-digitalocean-github-and-docker/

**Comment by Frozies** [comment]
Shutting down still doesnt work.

**Comment by Frozies** [comment]
When deploying now, the docker application starts and is up and running. Im getting a time out from the ssh command script though. 

Eureka found the source code. https://github.com/appleboy/drone-ssh/blob/7344ac6529e663fe6555fb760cc766e0a81b9a2f/plugin.go

**Comment by Frozies** [comment]
Adding the -d that was missing. Action script finally working. 😓
